/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminOrganizationsRouteImport } from './routes/_app/admin/organizations'
import { Route as AppAdminPracticesRouteImport } from './routes/_app/admin/practices'
import { Route as AppAdminReferringPhysiciansRouteImport } from './routes/_app/admin/referring-physicians'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppDevUiRouteImport } from './routes/_app/dev.ui'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPracticesRoute = AppAdminPracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminReferringPhysiciansRoute =
  AppAdminReferringPhysiciansRouteImport.update({
    id: '/referring-physicians',
    path: '/referring-physicians',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppDevUiRoute = AppDevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/practices': typeof AppAdminPracticesRoute
  '/admin/referring-physicians': typeof AppAdminReferringPhysiciansRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/dev/ui': typeof AppDevUiRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/practices': typeof AppAdminPracticesRoute
  '/admin/referring-physicians': typeof AppAdminReferringPhysiciansRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/dev/ui': typeof AppDevUiRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/_app/admin/practices': typeof AppAdminPracticesRoute
  '/_app/admin/referring-physicians': typeof AppAdminReferringPhysiciansRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/dev/ui': typeof AppDevUiRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin'
    | '/admin/organizations'
    | '/admin/practices'
    | '/admin/referring-physicians'
    | '/admin/users'
    | '/dev/ui'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/'
    | '/admin/organizations'
    | '/admin/practices'
    | '/admin/referring-physicians'
    | '/admin/users'
    | '/dev/ui'
    | '/admin'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/_app/admin'
    | '/_app/'
    | '/_app/admin/organizations'
    | '/_app/admin/practices'
    | '/_app/admin/referring-physicians'
    | '/_app/admin/users'
    | '/_app/dev/ui'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/organizations': {
      id: '/_app/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/practices': {
      id: '/_app/admin/practices'
      path: '/practices'
      fullPath: '/admin/practices'
      preLoaderRoute: typeof AppAdminPracticesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/referring-physicians': {
      id: '/_app/admin/referring-physicians'
      path: '/referring-physicians'
      fullPath: '/admin/referring-physicians'
      preLoaderRoute: typeof AppAdminReferringPhysiciansRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/dev/ui': {
      id: '/_app/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof AppDevUiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminPracticesRoute: typeof AppAdminPracticesRoute
  AppAdminReferringPhysiciansRoute: typeof AppAdminReferringPhysiciansRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminPracticesRoute: AppAdminPracticesRoute,
  AppAdminReferringPhysiciansRoute: AppAdminReferringPhysiciansRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDevUiRoute: typeof AppDevUiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDevUiRoute: AppDevUiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
